#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
source $CONFIG_DIR/constants.sh

args=()

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

args+=(
  --bar
  position=bottom
  height=22
  color=$COLOR_BASE
  topmost=on
  notch_width=0
)

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

args+=(
  --default
  padding_left=8
  padding_right=8
  icon.font="FiraCode Nerd Font:Retina:12.0"
  label.font="FiraCode Nerd Font:Retina:12.0"
  icon.color=$COLOR_TEXT
  label.color=$COLOR_TEXT
  background.height=$BAR_HEIGHT
  background.padding_left=0
  background.padding_right=0
  icon.padding_left=16
  icon.padding_right=4
  label.padding_left=2
  label.padding_right=16
  icon.background.height=$BAR_HEIGHT
)

##### Adding Aerospace Workspaces Indicators #####
args+=(
  --add event aerospace_workspace_change
  --add event aerospace_windows_change
)

space_ids=()
for sid in "${WORKSPACES[@]}"; do
  space_ids+=("space.$sid")
  args+=(
    --add item space.$sid left
    --set space.$sid
    click_script="aerospace workspace $sid"
  )
done

args+=(
  --add bracket spaces "${space_ids[@]}"
  --set spaces
  script="$PLUGIN_DIR/aerospace.sh"
  --subscribe spaces aerospace_workspace_change
  --subscribe spaces aerospace_windows_change
  --subscribe spaces space_windows_change
)

##### Force all scripts to run the first time (never do this in a script) #####
args+=(--update)
sketchybar "${args[@]}"
