#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
source $CONFIG_DIR/constants.sh

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=bottom height=28 color=0xff020618 topmost=on notch_width=0

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=8
  padding_right=8
  icon.font="FiraCode Nerd Font:Retina:14.0"
  label.font="FiraCode Nerd Font:Retina:14.0"
  icon.color=0xffcad5e2
  label.color=0xffcad5e2
  background.height=28
  background.padding_left=0
  background.padding_right=0
  icon.padding_left=16
  icon.padding_right=4
  label.padding_left=0
  label.padding_right=16
  icon.background.height=28
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

##### Adding Aerospace workspace Indicators #####
sketchybar \
  --add event aerospace_workspace_change \
  --add event aerospace_windows_change

WORKSPACES=("1" "2" "3" "4" "5" "6" "7" "8" "9")
SPACE_IDS=()

for sid in "${WORKSPACES[@]}"; do
  SPACE_IDS+=("space.$sid")
  sketchybar \
    --add item space.$sid left \
    --set space.$sid \
    click_script="aerospace workspace $sid"
done

sketchybar --add bracket spaces "${SPACE_IDS[@]}" \
  --set spaces \
  script="$PLUGIN_DIR/aerospace.sh" \
  --subscribe spaces aerospace_workspace_change \
  --subscribe spaces aerospace_windows_change

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# sketchybar --add item chevron left \
#   --set chevron icon= label.drawing=off \
#   --add item front_app left \
#   --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#   --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# sketchybar --add item clock right \
#   --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
#   --add item volume right \
#   --set volume script="$PLUGIN_DIR/volume.sh" \
#   --subscribe volume volume_change \
#   --add item battery right \
#   --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#   --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
